### ISSUE TITLE
python3 -m pip install librabbitmq # raises a SyntaxError

### ISSUE THREAD

**Issue by cclauss** [celery/librabbitmq#100] opened 2017-09-16 09:42 UTC
$ python3 -m pip install librabbitmq  # appears to be fixed in #99 
```
Collecting librabbitmq
  Using cached librabbitmq-1.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0n/hps2hvvd765bt55ydqqdhf4m0000gn/T/pip-build-h50ra2mh/librabbitmq/setup.py", line 191
        except Exception, exc:
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0n/hps2hvvd765bt55ydqqdhf4m0000gn/T/pip-build-h50ra2mh/librabbitmq/
```

Workaround: `python3 -m pip install git+https://github.com/celery/librabbitmq`
* However #99 appears to be a safer way to go until there is [release > 1.6.1](https://github.com/celery/librabbitmq/releases) _Nov 2014_.  @auvipy

**Comment by 7h3kk1d** [comment] 2017-10-09 15:22
I don't think this is an issue. The current deployed PyPi package doesn't have python3 support. I think once master has been tested it will go through the process to be published. Not sure what that process is though.

**Comment by cclauss** [comment] 2017-10-09 15:28
I can close this issue once that release goes public.

**Comment by Shraa** [comment] 2017-11-22 18:56
+ python -m pip install celery[librabbitmq]
...
Collecting librabbitmq>=1.5.0; extra == "librabbitmq" (from celery[auth,librabbitmq,msgpack,redis,yaml])
  Downloading librabbitmq-1.6.1.tar.gz (529kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rcqi168i/librabbitmq/setup.py", line 191
        except Exception, exc:
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rcqi168i/librabbitmq/

**Comment by cclauss** [comment] 2017-11-22 20:45
```python
except Exception, exc:  # Python 2 only

except Exception as exc:  # Python 2 and 3
```

**Comment by auvipy** [comment] 2018-01-15 11:01
https://github.com/celery/librabbitmq/releases/tag/v2.0.0 can you try this

**Comment by harishanand95** [comment] 2018-01-17 15:56
@auvipy @matusvalo Could you show how to install it in python3.6?

**Comment by matusvalo** [comment] 2018-01-19 17:09
librabbitmq 2.0 is not published yet in pypi, so currently only way is to install it from source. See https://github.com/celery/librabbitmq#using-the-development-version

**Comment by matusvalo** [comment] 2018-01-19 17:42
@auvipy just a note. You have created v2.0.0 tag but this tag cannot be distributed via pypi because setup.py version is used version from header file (see my PR #106 ) not bumped in __init__.py file.

**Comment by auvipy** [comment] 2018-01-20 09:41
merged and new tag created.

**Comment by ergo** [comment] 2018-03-02 14:37
Awesome, any news when new version will get released?

**Comment by thedrow** [comment] 2018-03-07 16:11
@ergo I haven't had the time to write the release notes yet.

**Comment by thedrow** [comment] 2018-03-07 16:11
I'm closing this issue since the problem is fixed. 2.0.0 will be released as soon as possible.

**Closed by thedrow** 2018-03-07 16:11 UTC

**Comment by ihor-nahuliak** [comment] 2018-03-10 16:09
The same issue. I'm waiting for the release with the fix. Does anybody know in which version there is no this issue?

**Comment by cclauss** [comment] 2018-03-10 16:19
https://github.com/celery/librabbitmq/issues/100#issuecomment-359029550

**Comment by ezhouyang** [comment] 2018-05-30 03:47
1、Follow https://github.com/celery/librabbitmq install desc
2、Download source code
3、find & change setup.py code [ except Exception, exc ]  to  [ except Exception as exc ] 
4、install will done
